### ISSUE TITLE
Switch to LP-compatible Newtonsoft

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.Security.OAuth2#34]
I guessed the version number incorrectly :(

**Comment by omsmith** [comment]
Alternatively, update LP and friends.

Gogo Newtonsoft 8.0.2!

**Comment by j3parker** [comment]
Hm. That's a good point.
I'll ask around. I know some folks that were involved in the last one.

**Comment by j3parker** [comment]
Deeming "close enough", but upgrading our Newtonsofts in LP etc. is still on my list
